language: node_js
node_js:
  - 6

install:
  - npm install
  - npm install -g firebase-tools

script:
  - gulp test

after_success:
  - gulp build
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "develop" && firebase deploy --token ${FIREBASE_TOKEN}

cache:
  directories:
    - node_modules
