language: node_js
node_js:
  - 6

install:
  - npm install
  - npm install -g firebase-tools

script:
  - npm test
  
after_success:
  - firebase deploy --email ${FIREBASE_USERNAME} --password ${FIREBASE_PASSWORD}
