language: node_js
node_js:
  - 6

install:
  - npm install
  - npm install -g firebase-tools

script:
  - npm test
  
after_success:
  - gulp build
  - test $TRAVIS_BRANCH = "development" && firebase deploy --token ${FIREBASE_TOKEN}
