language: node_js
node_js:
  - 6

install:
  - npm install
  - npm install -g firebase-tools
  - npm install -g angular-cli

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "develop" && ng build && firebase deploy --token ${FIREBASE_TOKEN}

cache:
  directories:
    - node_modules
